name: OWASP-Juice-Shop-Automation | Playwright Tests

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testenv

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          python -m playwright install --with-deps

      - name: Build and run Juice Shop Docker container
        run: |
          docker pull bkimminich/juice-shop
          docker run -d --name juice-shop -p 3000:3000 bkimminich/juice-shop

      - name: Wait for Juice Shop to be ready
        run: |
          for i in {1..30}; do
            curl -sSf http://localhost:3000 && break || echo "Waiting for Juice Shop to be ready..."
            sleep 10
          done

      - name: Run tests
        env:
          INVALID_EMAIL: ${{ secrets.INVALID_EMAIL }}
          INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SQL_EMAIL: ${{ secrets.SQL_EMAIL }}
          XSS_SCRIPT: ${{ secrets.XSS_SCRIPT }}
        run: |
          pytest -s --html=report.html --self-contained-html

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.html
